server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
  compression:
    enabled: true
    min-response-size: 256
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
  forward-headers-strategy: framework

spring:
  application:
    name: aws-cloud-watch
  profiles:
    active: local

# Logging
logging:
  config: classpath:logback-file.xml
  pattern:
    console: "%clr([%d{yyyy-MM-dd HH:mm:ss.SSS XXX, Asia/Seoul}]){faint} %clr([%5p]) %clr([%15.15t]){faint} %clr([%-40.40logger{39}]){cyan} %clr(:){faint} %m%n"
  level:
    root: INFO
    org.springframework: WARN
    com.example.s3: INFO
    com.amazonaws.util.EC2MetadataUtils: ERROR # amazon socket error.

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    persistAuthorization: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  paths-to-match:
    - /aws/**

#aws config
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
